<%

writeJavaClass(false, controllerPkg + ".CommonController", #{
    java_extends("Controller");
    java_imports(
        "com.jfinal.core.Controller"
    );
%>
    public void index() {
        render("/index");
    }
<%
});
%>