<%

var table_sqlname = currtable.sqlName;
var entity = currtable.entity;
var entityUpperFirst = entity@upperFirst();

writeJavaClass(false, validatorPkg + "."+ entityUpperFirst +"Validator", #{
    java_extends("Validator");
    java_imports(
        modelPkg + "." + entityUpperFirst,
        "com.jfinal.core.Controller",
        "com.jfinal.validate.Validator"
    );
%>
    protected void validate(Controller controller) {
<% 
    //All Columns
    for (column : currtable.columns){
        if(!column.ispk){
            var col_stype = column.javaSimpleType;
            var col_opti = column.optional;
            var col_sqlname = column.sqlName;
            var col_size = column.size;
            if(!column.optional){
                if(col_stype == "String" && col_size >0){
%>
        //${column.remarks}
        validateString("${entity}.${col_sqlname}", 1, ${col_size},"${col_sqlname}Msg", "请输入内容!");<%
                } else if(col_stype@in_arr(["Integer","Short"])){
%>
        //${column.remarks}
        validateInteger("${entity}.${col_sqlname}", Integer.MIN_VALUE, Integer.MAX_VALUE,"${col_sqlname}Msg", "请输入内容!");<%
                } else {
%>
        //${column.remarks}
        validateRequired("${entity}.${col_sqlname}","${col_sqlname}Msg", "请输入内容!");<%
}
            }
        }
    }
%>
    }

    protected void handleError(Controller controller) {
        controller.keepModel(${entityUpperFirst}.class);

        String actionKey = getActionKey();
        if (actionKey.equals("/admin/${entity}/save")) {
            controller.render("/admin/${entity}/add");
        } else if (actionKey.equals("/admin/${entity}/update")) {
            controller.render("/admin/${entity}/edit");
        }
    }
<%
});
%>