<%


var table_sqlname = currtable.sqlName;
var entity = currtable.entity;
var entityUpperFirst = entity@upperFirst();

writeJavaClass(false, controllerPkg + "."+ entityUpperFirst +"Controller", #{
    java_extends("Controller");
    java_imports(
        modelPkg + "." + entityUpperFirst,
        "com.jfinal.core.Controller"
    );
%>
    public void index() {
        setAttr("${entity}Page", ${entityUpperFirst}.dao.paginate(getParaToInt(0, 1), 10, "SELECT *", "FROM ${db.tablePrefix}${table_sqlname} ORDER BY ${currtable.idColumn.sqlName} ASC"));
        render("/${entity}/index");
    }
<%
});
%>