<%

var table_sqlname = currtable.sqlName;
var entity = currtable.entity;
var entityUpperFirst = entity@upperFirst();

writeJavaClass(false, modelPkg + "."+ entityUpperFirst, #{
    java_extends("Model<"+entityUpperFirst+">");
    java_imports(
        "com.jfinal.plugin.activerecord.Model"
    );
%>
    public static final ${entityUpperFirst} dao = new ${entityUpperFirst}();
    //TODO: 生成外键getter

    //Note: 类型仅供参考
<% 
    //All Columns
    for (column : currtable.columns){
%>
    //${column.simpleType} ${column.sqlName}; //${column.remark}<%
    }
%>
<%
});
%>