<%

var entity = currtable.sqlName;
writeWebFile(false, "WEB-INF/templates/"+entity+"/index.wit", #{
%>\<%

var ${entity}Page;
layout(function(){
%>
<h1>${entity}
</h1>
<div class="table_box">
    <table class="list">
        <tbody>
            <tr>
        <% for(column : currtable.columns) {%>
                <th width="10%">${column.remarks}</th>
        <% } %>
            </tr>
            \<% for(${entity} : ${entity}Page.list){ %>
            <tr>
        <% for(column : currtable.columns) {%>
                <td style="text-align:left;">\${${entity}.${column.sqlName}}</td>
        <% } %>
            </tr>
            \<% } %>
        </tbody>
    </table>
    \<% paginate(${entity}Page.pageNumber, ${entity}Page.totalPage, "\${BASE_PATH}/${entity}/"); %>
</div>
\<% }); %>
<% }); %>