<%

var entity = currtable.entity;
writeWebFile(false, "WEB-INF/templates/admin/"+entity+"/add.wit", #{
%>\<% layout(function(){ %>
<h1>${currtable.remark}管理 ---&gt; 创建${currtable.remark}
</h1>
<div class="form_box">
    <form action="\${BASE_PATH}/admin/${entity}/save" method="post">
        \<% include "_form"; %>
    </form>
</div>
\<% }); %>
<% }); %>