<%

var entity = currtable.entity;
writeWebFile(false, "WEB-INF/templates/admin/"+entity+"/index.wit", #{
%>\<%

var ${entity}Page;
layout(function(){
%>
<h1>${currtable.remark}管理&nbsp;&nbsp;
    <a href="\${BASE_PATH}/admin/${entity}/add">创建${currtable.remark}</a>
</h1>
<div class="table_box">
    <table class="list">
        <tbody>
            <tr>
        <% for(column : currtable.columns) { %>
                <th width="10%">${column.remark}</th>
        <% } %>
                <th width="12%">操作</th>
            </tr>
            \<% for(${entity} : ${entity}Page.list){ %>
            <tr>
        <% for(column : currtable.columns){ %>
                <td style="text-align:left;">\${${entity}.${column.sqlName}}</td>
        <% } %>
                <td style="text-align:left;">
                    &nbsp;&nbsp;<a href="\${BASE_PATH}/admin/${entity}/delete/\${${entity}.id}">删除</a>
                    &nbsp;&nbsp;<a href="\${BASE_PATH}/admin/${entity}/edit/\${${entity}.id}">修改</a>
                </td>
            </tr>
            \<% } %>
        </tbody>
    </table>
    \<% paginate(${entity}Page.pageNumber, ${entity}Page.totalPage, "\${BASE_PATH}/admin/${entity}/"); %>
</div>
\<% }); %>
<% }); %>